echo ${ASTRA_CLUSTER_ID}
echo ${ASTRA_CLUSTER_REGION}
echo ${ASTRA_DB_USERNAME}
echo ${ASTRA_DB_PASSWORD}

docker run -it --rm --name astra-explorer-run -e ASTRA_CLUSTER_ID=${ASTRA_CLUSTER_ID} -e ASTRA_CLUSTER_REGION=${ASTRA_CLUSTER_REGION} -e ASTRA_DB_USERNAME=${ASTRA_DB_USERNAME} -e ASTRA_DB_PASSWORD="${ASTRA_DB_PASSWORD}" astra-explorer
